FROM public.ecr.aws/lambda/python:3.11

# Actualizar pip
RUN pip install --upgrade pip --quiet

# Copiar requirements de Lambda y el código
COPY requirements-lambda.txt .
RUN pip install -r requirements-lambda.txt --no-cache-dir --only-binary=:all:

# Copiar el código fuente
COPY config.py .
COPY src/ src/

# Handler de Lambda
CMD ["src.predict_lambda.lambda_handler"]
